### ISSUE TITLE
MythicBeasts provider unauthorized

### ISSUE THREAD

**Issue by solvaholic** [solvahol/dns#24]
## Description

When I set MYTHIC_BEASTS_PASSWORD repository secret, and add the environment variable to the workflow:

```yaml
      - name: Run `octodns-sync` with ${{ needs.meta.outputs.config }}
        id: octodns-sync
        uses: solvaholic/octodns-sync@main
        # TODO: When no changes, skip the rest of this workflow?
        with:
          config_path: ${{ needs.meta.outputs.config }}
          octodns_ref: master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.route53_aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.route53_aws_secret_access_key }}
          MYTHIC_BEASTS_PASSWORD: ${{ secrets.mythic_beasts_password }}
```

And the provider to public.yaml:

```yaml
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: .
  mythicbeasts:
    class: octodns.provider.mythicbeasts.MythicBeastsProvider
    passwords:
      solvahol.org.: env/MYTHIC_BEASTS_PASSWORD
  route53:
    class: octodns.provider.route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY

zones:
  solvahol.org.:
    sources:
      - config
    targets:
      - mythicbeasts
      - route53
```

The workflow [fails](https://github.com/solvahol/dns/runs/4275227991?check_suite_focus=true#step:4:212) with:

```text
octodns.provider.mythicbeasts.MythicBeastsUnauthorizedException: ('Mythic Beasts unauthorized for zone: solvahol.org', 'solvahol.org')
```

Using `curl` with the same password authenticates successfully.

## Expected Behavior

Mythic Beasts authentication succeeds, like it does with `curl`:

```text
% _pass="PASSWORD"
% _data="domain=solvahol.org&amp;password=$_pass&amp;command=LIST"
% curl --data "$_data" https://dnsapi.mythic-beasts.com/
@ 86400 NS  ns1.mythic-beasts.com.
@ 86400 NS  ns2.mythic-beasts.com.
```

## Actual Behavior

This exception, thrown [in mythicbeasts.py](https://github.com/octodns/octodns/blob/49773cbcf7a0aa729623e89d7f13c95cd38b95ec/octodns/provider/mythicbeasts.py#L131-L132):

```text
octodns.provider.mythicbeasts.MythicBeastsUnauthorizedException: ('Mythic Beasts unauthorized for zone: solvahol.org', 'solvahol.org')
```

## Possible Fix

🤷 

## Steps to Reproduce

1. Configure octodns to use mythicbeasts provider
1. Configure repository secret and workflow to pass MYTHIC_BEASTS_PASSWORD env variable
1. Run workflow

## Context

I'd like to transfer DNS from Route53 to Mythic Beasts. This issue is blocking me.

## Your Environment

* Version used: main?
* Link to your project: .
